# from auto import Database
#
# class values:
#         Database(-21.0, 'GLOBAL IME BANK LTD')
#         Database(0.0, ' Sunrise Bank Debenture')
#         Database(10.0, ' SBL Debenture  ')
#         Database(-2.0, ' Aarambha Chautari Laghubitta Bittiya Sanstha Limited ')
#         Database(-1.0, ' Agriculture Development Bank Limited ')
#         Database(1.0, ' Ajod Insurance Limited')
#         Database(8.0, ' Ankhu Khola Jalvidhyut Company Ltd ')
#         Database(16.0, 'Api Power Company Ltd')
#         Database(18.0, 'Arun Kabeli Power Ltd')
#         Database(17.0, 'Arun Valley Hydropower Development')
#         Database(1.0, 'Asha Laghubitta Bittiya Sanstha Ltd ')
#         Database(5.0, ' Asian Life Insurance Co Limited ')
#         Database(-3.0, ' Bank of Kathmandu Ltd')
#         Database(13.0, ' Barun Hydropower  ')
#         Database(0.0, ' Best Finance Company Ltd')
#         Database(-5.0, ' Bishal Bazar Company Limited ')
#         Database(69.0, ' Bottlers Nepal (Terai) Limited ')
#         Database(4.0, ' Butwal Power Company Limited ')
#         Database(0.0, ' Central Finance Co Ltd')
#         Database(0.0, ' Century Commercial Bank Ltd')
#         Database(0.0, ' Century Commercial Bank Ltd Promoter Share')
#         Database(8.0, ' Chhimek Laghubitta Bikas Bank Limited ')
#         Database(12.0, ' Chhyangdi Hydropower Ltd')
#         Database(5.0, ' Chilime Hydropower Company Limited ')
#         Database(3.0, ' Citizen Bank International Limited ')
#         Database(58.0, ' Citizen Investment Trust ')
#         Database(-0.24, ' Citizens Mutual Fund')
#         Database(2.0, ' Civil Bank Ltd ')
#         Database(-10.0, ' Civil Laghubitta Bittiya Sanstha Ltd')
#         Database(9.0, ' Corporate Development Bank Limited ')
#         Database(-2.0, ' Deprosc Laghubitta Bittiya Sanstha Limited ')
#         Database(8.0, ' Dibyashwori Hydropower Ltd')
#         Database(-1.0, ' Everest Bank Limited ')
#         Database(0.0, ' Everest Insurance  Ltd')
#         Database(-1.0, ' Excel Development Bank Ltd')
#         Database(1.0, ' First Micro Finance Development Bank Ltd')
#         Database(-13.0, ' Forward Community Microfinance Bittiya Sanstha Ltd')
#         Database(35.0, ' Ganapati Microfinance Bittiya Sanstha Limited')
#         Database(0.0, ' Garima Bikas Bank Limited')
#         Database(8.0, ' Ghalemdi Hydro Limited')
#         Database(-2.0, ' Ghodighoda Laghubitta Bittiya Sanstha Ltd')
#         Database(0.0, ' Global IME Bank Limited')
#         Database(-5.0, ' Global IME Laghubitta Bittiya Sanstha Ltd')
#         Database(0.02, ' Global IME Samunnat Scheme')
#         Database(2.0, ' Goodwill Finance Ltd')
#         Database(-7.0, ' Grameen Bikas Laghubitta Bittiya Sanstha Ltd')
#         Database(2.0, ' Green Development Bank Ltd')
#         Database(5.0, ' Guheshowori Merchant Bank & Finance')
#         Database(2.0, ' Gurans Laghubitta Bittiya Sanstha Limited')
#         Database(-7.0, ' Gurans Life Insurance Company Ltd')
#         Database(-2.0, ' Gurkhas Finance Ltd')
#         Database(9.0, ' Himal Dolakha Hydropower Company Limited')
#         Database(8.0, ' Himalaya Urja Bikas Company Limited')
#         Database(-1.0, ' Himalayan Bank Limited')
#         Database(2.0, ' Himalayan Distillery Limited')
#         Database(0.0, ' Himalayan General Insurance Ltd')
#         Database(6.0, ' Himalayan Power Partner Ltd')
#         Database(15.0, ' Hydorelectricity Investment and Development Company Ltd')
#         Database(3.0, ' ICFC Finance Limited')
#         Database(-5.0, ' IME General Insurance Ltd')
#         Database(26.0, ' Infinity Laghubitta Bittiya Sanstha Limited')
#         Database(2.0, ' Janaki Finance Ltd')
#         Database(25.0, ' Janautthan Samudayic Laghubitta Bikas Bank Ltd')
#         Database(0.0, ' Joshi Hydropower Development Company Ltd')
#         Database(1.0, ' Jyoti Bikas Bank Limited')
#         Database(-15.0, ' Kalika Microcredit Development Bank Ltd')
#         Database(11.0, ' Kalika power Company Ltd')
#         Database(4.0, ' Kamana Sewa Bikas Bank Limited')
#         Database(-2.0, ' Karnali Development Bank Limited ')
#         Database(8.0, ' Khanikhola Hydropower Ltd ')
#         Database(1.0, ' Kumari Bank Limited ')
#         Database(1.0, ' Laxmi Bank Limited ')
#         Database(0.03, ' Laxmi Equity Fund ')
#         Database(-4.0, ' Laxmi Laghubitta Bittiya Sanstha Ltd')
#         Database(0.03, ' Laxmi Unnati Kosh ')
#         Database(5.0, ' Liberty Energy Company Limited ')
#         Database(-18.0, ' Life Insurance   Nepal ')
#         Database(0.0, ' Lumbini Bikas Bank  Ltd ')
#         Database(0.0, ' Lumbini General Insurance Ltd ')
#         Database(0.0, ' Machhapuchhre Bank Limited ')
#         Database(-2.0, ' Mahalaxmi Bikas Bank  Ltd ')
#         Database(0.0, ' Mahila Sahayatra Microfinance Bittiya Sanstha Ltd')
#         Database(-1.0, ' Manjushree Finance Ltd')
#         Database(1.0, ' Mega Bank Nepal Ltd')
#         Database(3.0, ' Mero Microfinance Bittiya Sanstha Ltd')
#         Database(2.0, ' Mirmire Microfinance Development Bank Ltd')
#         Database(-6.0, ' Miteri Development Bank Limited ')
#         Database(-8.0, ' Mithila LaghuBitta Bittiya Sanstha Limited ')
#         Database(11.0, ' Mountain Hydro Nepal Limited ')
#         Database(0.0, ' Muktinath Bikas Bank Ltd')
#         Database(3.0, ' Multipurpose Finance Company Limited ')
#         Database(-0.15, ' NABIL BALANCED FUND')
#         Database(1.0, ' Nabil Bank Limited ')
#         Database(0.09, ' Nabil Equity Fund ')
#         Database(-3.0, ' Nadep Laghubittiya bittya Sanstha Ltd')
#         Database(1.0, ' National Hydro Power Company Limited ')
#         Database(-7.0, ' National Life Insurance Ltd')
#         Database(30.0, ' National Microfinance Bittiya Sanstha Ltd')
#         Database(-3.0, ' Neco Insurance Ltd')
#         Database(-2.0, ' Nepal Bangladesh Bank Limited ')
#         Database(2.0, ' Nepal Bank Limited ')
#         Database(1.0, ' Nepal Credit And Commercial Bank Limited ')
#         Database(2.0, ' Nepal Doorsanchar Comapany Limited ')
#         Database(0.0, ' Nepal Finance  Ltd ')
#         Database(15.0, ' Nepal Hydro Developers  Ltd ')
#         Database(-1.0, ' Nepal Insurance    Ltd ')
#         Database(3.0, ' Nepal Investment Bank Limited ')
#         Database(-2.0, ' Nepal Investment Bank  Ltd Promoter Share ')
#         Database(0.0, ' Nepal Life Insurance    Ltd ')
#         Database(-5.0, ' Nepal Reinsurance Company Limited ')
#         Database(-2.0, ' Nepal SBI Bank Limited ')
#         Database(-3.0, ' Nepal Seva Laghubitta Bittiya Sanstha  Ltd ')
#         Database(-3.0, ' Nerude Laghubita Bikas Bank Limited ')
#         Database(13.0, ' Ngadi Group Power  Ltd ')
#         Database(0.0, ' NIBL Pragati Fund ')
#         Database(-0.01, ' NIBL Samriddhi Fund 1 ')
#         Database(0.15, ' NIC Asia Balanced Fund ')
#         Database(1.0, ' NIC Asia Bank  Ltd ')
#         Database(-0.14, ' NIC Asia Growth Fund ')
#         Database(0.0, ' Nirdhan Utthan Laghubitta Bittiya Sanstha Limited ')
#         Database(-3.0, ' NLG Insurance Company  Ltd ')
#         Database(4.0, ' NMB Microfinance Bittiya Sanstha  Ltd ')
#         Database(0.06, ' NMB 50 ')
#         Database(0.0, ' NMB Bank Limited ')
#         Database(0.0, ' NMB Hybrid Fund L-1 ')
#         Database(0.0, ' NRN Infrastructure and Development Limited ')
#         Database(7.0, ' NRN Lagubitta Bittiya Sanstha Limited ')
#         Database(2.0, ' Oriental Hotels Limited ')
#         Database(6.0, ' Panchakanya Mai Hydropower Ltd ')
#         Database(7.0, ' Panchthar Power Compant Limited ')
#         Database(0.0, ' Pokhara Finance  Ltd ')
#         Database(1.0, ' Prabhu Bank Limited ')
#         Database(-6.0, ' Prabhu Insurance  Ltd ')
#         Database(-3.0, ' Premier Insurance    Ltd ')
#         Database(-1.0, ' Prime Commercial Bank  Ltd ')
#         Database(-1.0, ' Prime Life Insurance Company Limited ')
#         Database(2.0, ' ProgressiveFinance Limited ')
#         Database(-4.0, ' Prudential Insurance    Ltd ')
#         Database(-3.0, ' Radhi Bidyut Company Ltd ')
#         Database(11.0, ' Rairang Hydropower Development Company  Ltd ')
#         Database(-188.0, ' Rastriya Beema Company Limited ')
#         Database(71.0, ' Rastriya Beema Company Limited Promoter Share ')
#         Database(10.0, ' RASUWAGADHI HYDROPOWER COMPANY LIMITED ')
#         Database(-3.0, ' Reliance Finance  Ltd ')
#         Database(-13.0, ' Reliance Life Insurance Limited ')
#         Database(13.0, ' Ridi Hydropower Development Company  Ltd ')
#         Database(-4.0, ' RMDC Laghubitta Bittiya Sanstha  Ltd ')
#         Database(-2.0, ' RSDC Laghubitta Bittiya Sanstha  Ltd ')
#         Database(-4.0, ' SABAIKO LAGHUBITTA BITTIYA SANSTHA LIMITED ')
#         Database(-6.0, ' Sadhana Laghubitta Bittiya Sanstha Limited ')
#         Database(-7.0, ' Sagarmatha Insurance    Ltd ')
#         Database(270.0, ' Salt Trading Corporation ')
#         Database(-2.0, ' Samriddhi Finance Company Limited ')
#         Database(-2.0, ' Samudayik Laghubitta Bittiya Sanstha Limited ')
#         Database(-11.0, ' Sana Kisan Bikas Bank Ltd ')
#         Database(-1.0, ' Sanima Bank Limited ')
#         Database(5.0, ' Sanima Bank Limited Debenture ')
#         Database(-0.05, ' Sanima Equity Fund ')
#         Database(6.0, ' Sanima Mai Hydropower  Ltd ')
#         Database(13.0, ' SANJEN JALAVIDHYUT COMPANY LIMITED ')
#         Database(6.0, ' Saptakoshi Development Bank Ltd ')
#         Database(-2.0, ' Shangrila Development Bank  Ltd ')
#         Database(-14.0, ' Shikhar Insurance    Ltd ')
#         Database(-2.0, ' Shine Resunga Development Bank  Ltd ')
#         Database(1.0, ' SHIVAM CEMENTS LTD ')
#         Database(5.0, ' Shree Investment Finance    Ltd ')
#         Database(-1.0, ' Siddhartha Bank Limited ')
#         Database(0.04, ' Siddhartha Equity Fund ')
#         Database(-1.0, ' Siddhartha Insurance  Ltd ')
#         Database(-1.0, ' Sindhu Bikash Bank Ltd ')
#         Database(2.0, ' Soaltee Hotel Limited ')
#         Database(-18.0, ' Sparsha Laghubitta Bittiya Sanstha Limited ')
#         Database(1.0, ' Standard Chartered Bank Limited ')
#         Database(0.0, ' Sunrise Bank Limited ')
#         Database(-0.1, ' Sunrise First Mutual Fund ')
#         Database(-11.0, ' Support Microfinance Bittiya Sanstha  Ltd ')
#         Database(0.0, ' Surya Life Insurance Company Limited ')
#         Database(17.0, ' Suryodaya Laghubitta Bittiya Sanstha  Ltd ')
#         Database(0.0, ' Swabalamban Laghubitta Bittiya Sanstha Limited ')
#         Database(-1.0, ' Swabhimaan Laghubitta Bittiya Sanstha Limited ')
#         Database(-10.0, ' Swarojgar Laghu Bitta Bikas Bank  Ltd ')
#         Database(18.0, ' Synergy Power Development  Ltd ')
#         Database(5.0, ' Taragaon Regency Hotel Limited ')
#         Database(-2.0, ' Tinau Mission Development Bank Limited ')
#         Database(-396.0, ' Unilever Nepal Limited ')
#         Database(7.0, ' Union Hydropower Limited ')
#         Database(22.0, ' United Finance  Ltd ')
#         Database(5.0, ' United Insurance   (Nepal)  Ltd ')
#         Database(13.0, ' United Modi Hydropower  Ltd ')
#         Database(3.0, ' UNIVERSAL POWER COMPANY LTD ')
#         Database(32.0, ' Unnati Sahakarya Laghubitta Bittiya Sanstha Limited ')
#         Database(18.0, ' Upper Tamakoshi Hydropower Ltd ')
#         Database(-1.0, ' Vijaya laghubitta Bittiya Sanstha  Ltd ')
#
#
#
#
